version: 0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore -source "https://ci.appveyor.com/nuget/ark3-2s7q98k69s2y"
build:
  verbosity: minimal
on_success:
- ps: >-
    Set-Location -Path .\Dewey.CLI\bin\$env:CONFIGURATION

    choco pack --version $env:APPVEYOR_BUILD_VERSION

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
